Allow configuration of how often winning alternatives are recalculated (#501)
* Rubocop: Update obsolete rule names

I saw these warnings on Rubocop 0.50.0:

    Error: The `Style/MethodCallParentheses` cop has been renamed to `Style/MethodCallWithoutArgsParentheses`.
    (obsolete configuration found in /Users/pat/academia/projects/split/.rubocop.yml, please update it)
    The `Style/OpMethods` cop has been renamed and moved to `Naming/BinaryOperatorParameter`.
    (obsolete configuration found in /Users/pat/academia/projects/split/.rubocop.yml, please update it)

* Allow configuration of how often winning alternatives are recalculated

If you're running A/B tests for a short period of time, the "Probability
of being Winner" numbers can be unhelpful or misleading.