Rubocop: Update obsolete rule names
I saw these warnings on Rubocop 0.50.0:

    Error: The `Style/MethodCallParentheses` cop has been renamed to `Style/MethodCallWithoutArgsParentheses`.
    (obsolete configuration found in /Users/pat/academia/projects/split/.rubocop.yml, please update it)
    The `Style/OpMethods` cop has been renamed and moved to `Naming/BinaryOperatorParameter`.
    (obsolete configuration found in /Users/pat/academia/projects/split/.rubocop.yml, please update it)